name: Detect Single Changed Submodule

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  find-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Get changed submodule
        run: |
          changes=$(git diff --name-only origin/master...HEAD widgets/)
          if [ -z "$changes" ]; then
            echo "No submodule changes detected."
          else
            echo "The following submodules were added or updated:"
            echo "$changes"
          fi

      